version: "3.8"
services:
  Hexapod:
    image: hexapod:latest
    container_name: hexapod_latest
    volumes:
#     - ./src:/app/src
      - /var/run/dbus/:/var/run/dbus/:z
      - /dev/input/:/dev/input/
    privileged: true
    entrypoint: bash entry_point.sh
