services:
  Hexapod:
    image: hexapod:latest
    container_name: hexapod_latest
    volumes:
     - ./src:/app/src
     - /var/run/dbus/:/var/run/dbus/:z
     - /dev/ttyAMA0:/dev/ttyAMA0:rw
     - /dev/input/:/dev/input/
    privileged: true
    entrypoint: ["bash", "/app/src/idle_entry_point.sh"]
