services:
  Hexapod:
    image: hexapod:latest
    container_name: hexapod_latest
    volumes:
      - ./src:/app/src
      - /var/run/dbus/:/var/run/dbus/:z
      - /dev/ttyAMA0:/dev/ttyAMA0:rw
      - /dev/input/:/dev/input/  # Pass all input devices
      - /tmp/.X11-unix:/tmp/.X11-unix  # Share XWayland socket
      - /run/user/1002:/run/user/1002  # Share Mutter XWayland auth
    environment:
      - DISPLAY=:0
      - XAUTHORITY=/root/.Xauthority  # Set correct X auth file inside container
      - QT_QPA_PLATFORM=xcb  # Force Qt to use XWayland
    devices:
      - /dev/dri:/dev/dri  # Necessary for graphical applications
    privileged: true
    entrypoint: ["bash", "/app/src/idle_entry_point.sh"]
