version: "3.8"
services:
  Hexapod:
    image: hexapod:latest
    container_name: hexapod_latest
    volumes:
     - ./src:/app/src
     - /var/run/dbus/:/var/run/dbus/:z
    privileged: true
    entrypoint: ["bash", "/app/src/dev_entry_point.sh"]
